spring.application.name=note

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/note_db
spring.datasource.username=postgres
spring.datasource.password=admin

# JPA Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
spring.jackson.serialization.fail-on-empty-beans=false

# Server Configuration
server.port=8084

